In [ ]:
data = [[0,1],[3,4],[5,6]]

In [3]:
import numpy as np
z= np.array([1,2,3],dtype = 'f')
z.astype(float)

array([1., 2., 3.])

In [16]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.max(axis = 1)

array([ 4,  8, 12])

In [21]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])
np.concatenate((x,y),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [54]:
a_mean = a.mean(axis = 1)
a_mean = a_mean.reshape(3,1) * np.ones((3,4))
(a >a_mean).sum(axis = 1)

array([2, 2, 2])

In [56]:
arr_10 = np.random.random((10,10))
np.savetxt('data.csv',arr_10)
arr_10 = arr_10[::2,:] + arr_10[1::2,:]
arr_10 = arr_10[:,::2] + arr_10[:,1::2]
arr_sorted = np.sort(arr_10,axis = 1)
np.savetxt('sorted_data.csv',arr_sorted)

In [47]:
import numpy as np
values = list(map(int,input("12개 입력하세요").split()))
np.sort(values).reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = b.reshape(3,4)
result = b.mean(axis = 1)
result.reshape(3,1)


array([[ 2.5],
       [ 6.5],
       [10.5]])

In [26]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [33]:
a = np.array([11,11,12,13,14,15,16,17, 12,13,11,14,18,19,20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [31]:
X = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
X.flatten()
X[0] = 99
X

array([[99, 99, 99, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
np.vstack((a1,a2))
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [13]:
np.array((3,2))

array([3, 2])

In [12]:
np.ones(3)
np.ones((3,2))
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])